### PR TITLE
Added functionality to remove parts of the QR Code behind the logo

### PR DESCRIPTION
**Pull request by larstel**
I added the functionality to remove the points of the QR Code behind a logo. For design reasons I also created a border around the image without points.

To activate the functionality you have simply add "removeQrCodeBehindLogo" to the html props.

### CODE REVIEW

**Comment by gcoro** [comment]
Thanks for your PR :)

**Comment by victorpavlenko** [comment]
@larstel 
image
image

Trimming from top, and trimming from bottom, as you can see, this doesn't work very well.
If I add 3px (although it depends on ecLevel) will this work?
So make it the image size + 1/2px in addition to the offset

**Comment by larstel** [comment]
Hi @victorpavlenko , what do you mean by this doesn't working very well? The fact, that some dots are leaking out under the image border?

**Comment by davx1992** [comment]
@larstel  is it working as it was planned? Should those dots leak or not?

**Pull request merged**
